core/urls.py
from django.urls import path
from core import views
from core import auth
from django.contrib.auth.views import LoginView


app_name = "core"

urlpatterns = [
    path('preferences/', views.user_preferences_update, name='user_preferences'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth.user_logout, name="logout"),
    path('tst/', views.tst, name='tst'),
    path('register/', auth.register_user, name='register'),
    path('delete_account/', auth.delete_account, name='delete_account'),
]

movie_filter_pro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviefilter.urls')),
    path('', include('tmdb_adapter.urls')),
    path('', include('core.urls')),
    path('', include('vault.urls')),
    path('', include('plex.urls')),
    path('', include('tmdb.urls')),
    path('', include('kinorium.urls')),
    path('', include('web_logger.urls')),
    path('', include('kinozal_scan.urls')),
]


if settings.ENABLE_BROWSER_RELOAD:
    # django_browser_reload APP
    urlpatterns += path("__reload__/", include("django_browser_reload.urls")),
if settings.ENABLE_DEBUG_TOOLBAR:
    # add debug_toolbar APP
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
if settings.DEBUG:
    # add serve for Media during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # add serve for Static during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tmdb/urls.py
from django.urls import path
from tmdb import views

app_name = "tmdb"

urlpatterns = [
    path('tmdb/', views.tmdb_section, name='tmdb'),
    path('search_movies_dropdown/', views.search_movies_dropdown, name='search_movies_dropdown'),
    path('search_movies_fullpage/', views.search_movies_fullpage, name='search_movies_fullpage'),
    path('movie/<int:movie_id>/', views.movie, name='movie'),
    path('list_get_movies/<int:list_id>/', views.list_get_movies, name='list_get_movies'),

    path('list_create/<str:list_name>', views.list_create, name='list_create'),
    path('list_delete/<int:list_id>/', views.list_delete, name='list_delete'),
    path('list_rename/<int:list_id>/', views.list_rename, name='list_rename'),
]

vault/urls.py
from django.urls import path
from . import views

app_name = 'vault'

urlpatterns = [
    # Главная страница и список фильмов
    path('', views.MovieListView.as_view(), name='movie_list'),
    path('movies/', views.MovieListView.as_view(), name='movie_list'),
    path('movies/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('genre/<slug:slug>/', views.MovieByGenreView.as_view(), name='movie_by_genre'),

    # Поиск
    path('search/', views.SearchView.as_view(), name='search'),

    # Персоны
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='person_detail'),

    # Пользовательские списки
    path('my-lists/', views.MyListsView.as_view(), name='my_lists'),
    path('list/<int:pk>/', views.ListDetailView.as_view(), name='list_detail'),
    path('list/create/', views.ListCreateView.as_view(), name='list_create'),
    path('list/<int:pk>/edit/', views.ListUpdateView.as_view(), name='list_edit'),
    path('list/<int:pk>/delete/', views.ListDeleteView.as_view(), name='list_delete'),

    # HTMX эндпоинты для быстрых действий
    path('htmx/toggle-status/', views.toggle_movie_status, name='htmx_toggle_status'),
    path('htmx/rate-movie/', views.rate_movie, name='htmx_rate_movie'),
    path('htmx/remove-rating/', views.remove_rating, name='htmx_remove_rating'),
    path('htmx/add-to-list/', views.add_to_list, name='htmx_add_to_list'),
    path('htmx/remove-from-list/', views.remove_from_list, name='htmx_remove_from_list'),
    path('htmx/toggle-list-privacy/', views.toggle_list_privacy, name='htmx_toggle_list_privacy'),

    # Отзывы
    path('movie/<slug:slug>/review/', views.CreateReviewView.as_view(), name='create_review'),
    path('htmx/like-review/<int:pk>/', views.like_review, name='htmx_like_review'),
]

vault/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, JsonResponse
from django.db.models import Q, Avg, Count
from django.contrib import messages
from django.core.paginator import Paginator

from .models import (
    Movie, Person, Genre, UserList, UserListMovie,
    Rating, Review, MoviePerson
)
from .services.movie_status_service import MovieStatusService


class MovieListView(ListView):
    """Список всех фильмов"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        queryset = Movie.objects.filter(status='released').prefetch_related('genres', 'countries')

        # Сортировка
        order = self.request.GET.get('order', '-year')
        queryset = queryset.order_by(order)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['selected_genre'] = None
        return context


class MovieByGenreView(ListView):
    """Фильмы по жанру"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        self.genre = get_object_or_404(Genre, slug=self.kwargs['slug'])
        queryset = Movie.objects.filter(
            genres=self.genre,
            status='released'
        ).prefetch_related('genres', 'countries')

        order = self.request.GET.get('order', '-year')
        queryset = queryset.order_by(order)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['selected_genre'] = self.genre
        return context


class MovieDetailView(DetailView):
    """Детальная страница фильма"""
    model = Movie
    template_name = 'vault/movie_detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie = self.object

        # Статус фильма у пользователя
        if self.request.user.is_authenticated:
            context['movie_status'] = MovieStatusService.get_movie_status(
                self.request.user, movie
            )
            context['user_rating'] = context['movie_status']['rating']
        else:
            context['movie_status'] = {
                'in_watched': False,
                'in_will_watch': False,
                'in_wont_watch': False,
                'in_favorites': False,
                'rating': None,
            }
            context['user_rating'] = None

        # Отзывы
        context['reviews'] = movie.reviews.select_related('user').prefetch_related('likes')[:5]

        return context


class SearchView(ListView):
    """Поиск фильмов"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        query = self.request.GET.get('q', '')

        if query:
            queryset = Movie.objects.filter(
                Q(title__icontains=query) |
                Q(original_title__icontains=query) |
                Q(description__icontains=query)
            ).prefetch_related('genres', 'countries')
        else:
            queryset = Movie.objects.none()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


class PersonDetailView(DetailView):
    """Страница персоны (актер, режиссер и т.д.)"""
    model = Person
    template_name = 'vault/person_detail.html'
    context_object_name = 'person'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        person = self.object

        # Все фильмы персоны
        all_movies = MoviePerson.objects.filter(
            person=person
        ).select_related('movie').order_by('-movie__year')

        context['all_movies'] = all_movies
        context['movies_count'] = all_movies.count()

        # По ролям
        context['actor_movies'] = all_movies.filter(role='actor')
        context['director_movies'] = all_movies.filter(role='director')
        context['producer_movies'] = all_movies.filter(role='producer')

        # Статистика
        context['roles_count'] = all_movies.values('role').distinct().count()

        # Годы карьеры
        years = all_movies.values_list('movie__year', flat=True)
        if years:
            context['career_years'] = max(years) - min(years)
        else:
            context['career_years'] = 0

        return context


class MyListsView(LoginRequiredMixin, ListView):
    """Все списки пользователя"""
    model = UserList
    template_name = 'vault/my_lists.html'
    context_object_name = 'user_lists'

    def get_queryset(self):
        return UserList.objects.filter(
            user=self.request.user
        ).prefetch_related('list_movies').order_by('order', '-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Разделяем системные и пользовательские списки
        all_lists = self.get_queryset()
        context['system_lists'] = all_lists.filter(is_system=True)
        context['custom_lists'] = all_lists.filter(is_system=False)

        return context


class ListDetailView(LoginRequiredMixin, DetailView):
    """Детальная страница списка"""
    model = UserList
    template_name = 'vault/list_detail.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        # Пользователь может видеть только свои списки (или публичные - добавить позже)
        return UserList.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_list = self.object

        # Фильмы из списка
        list_movies = UserListMovie.objects.filter(
            user_list=user_list
        ).select_related('movie').prefetch_related('movie__genres')

        # Сортировка
        order = self.request.GET.get('order', '-added_at')
        if order == '-added_at':
            list_movies = list_movies.order_by('-added_at')
        elif order == '-year':
            list_movies = list_movies.order_by('-movie__year')
        elif order == '-imdb_rating':
            list_movies = list_movies.order_by('-movie__imdb_rating')
        elif order == 'title':
            list_movies = list_movies.order_by('movie__title')

        context['list_movies'] = list_movies
        context['movies'] = Movie.objects.filter(
            id__in=list_movies.values_list('movie_id', flat=True)
        )

        # Статистика
        movies = context['movies']
        context['avg_duration'] = movies.aggregate(Avg('duration'))['duration__avg']
        context['avg_rating'] = movies.aggregate(Avg('imdb_rating'))['imdb_rating__avg']

        # Популярные жанры
        context['top_genres'] = Genre.objects.filter(
            movies__in=movies
        ).annotate(count=Count('movies')).order_by('-count')[:5]

        return context


class ListCreateView(LoginRequiredMixin, CreateView):
    """Создание нового списка"""
    model = UserList
    template_name = 'vault/list_create.html'
    fields = ['name', 'description', 'is_public']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.list_type = 'custom'
        form.instance.is_system = False
        messages.success(self.request, 'Список успешно создан!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:list_detail', kwargs={'pk': self.object.pk})


class ListUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование списка"""
    model = UserList
    template_name = 'vault/list_create.html'
    fields = ['name', 'description', 'is_public']

    def get_queryset(self):
        # Только свои списки и не системные
        return UserList.objects.filter(user=self.request.user, is_system=False)

    def form_valid(self, form):
        messages.success(self.request, 'Список успешно обновлен!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:list_detail', kwargs={'pk': self.object.pk})


class ListDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление списка"""
    model = UserList
    success_url = reverse_lazy('vault:my_lists')

    def get_queryset(self):
        # Только свои списки и не системные
        return UserList.objects.filter(user=self.request.user, is_system=False)

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Список успешно удален!')
        return super().delete(request, *args, **kwargs)


class CreateReviewView(LoginRequiredMixin, CreateView):
    """Создание отзыва"""
    model = Review
    fields = ['title', 'text', 'review_type']

    def form_valid(self, form):
        movie = get_object_or_404(Movie, slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        form.instance.movie = movie
        messages.success(self.request, 'Отзыв успешно опубликован!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:movie_detail', kwargs={'slug': self.kwargs['slug']})


# ============== HTMX Views ==============

@login_required
def toggle_movie_status(request):
    """Переключить статус фильма (HTMX)"""
    if request.method == 'POST':
        movie_id = request.POST.get('movie_id')

vault/templates/vault.html
{% extends "base.html" %}

{% block body %}

    <div class="container-fluid d-flex flex-column">

        <!-- SEARCH BAR -->
        <div class="bg-body-tertiary border-bottom p-3 flex-shrink-0">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-7 col-lg-5"> <!-- Здесь ограничиваем ширину -->

                        <form hx-post="{% url 'vault:search_movies_fullpage' %}"
                              hx-target="#main-content"
                              hx-push-url="false"
                              class="d-flex w-100">

                            <div class="dropdown position-relative w-100">

                                <input type="search"
                                       id="movie-search-input"
                                       class="form-control"
                                       name="query"
                                       placeholder="Поиск фильма..."
                                       hx-post="{% url 'vault:search_movies_dropdown' %}"
                                       hx-trigger="input changed delay:500ms"
                                       hx-target="#search-results"
                                       hx-push-url="false"
                                       autocomplete="off"
                                       aria-expanded="false">

                                <ul class="dropdown-menu w-100"
                                    id="search-results"
                                    style="max-height: 300px; overflow-y: auto;">
                                </ul>
                            </div>
                        </form>

                        <script>
                            document.addEventListener('DOMContentLoaded', function () {
                                const searchInput = document.getElementById('movie-search-input');
                                const searchResults = document.getElementById('search-results');
                                const mainContent = document.getElementById('main-content');
                                const searchForm = searchInput.closest('form');

                                // Показываем меню при приходе данных
                                searchResults.addEventListener('htmx:afterSwap', function() {
                                    if (searchResults.children.length > 0) {
                                        searchResults.classList.add('show');
                                    }
                                });

                                //  Очищаем input после fullpage-поиска (Enter)
                                mainContent.addEventListener('htmx:afterSwap', function () {
                                    searchInput.value = '';
                                    searchResults.classList.remove('show');
                                });

                                // Клик вне input и dropdown — скрываем dropdown и очищаем строку поиска
                                document.addEventListener('click', function (e) {
                                    if (
                                        !searchInput.contains(e.target) &&
                                        !searchResults.contains(e.target)
                                    ) {
                                        searchResults.classList.remove('show');
                                        searchInput.value = '';
                                    }
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>

        <!-- MAIN LAYOUT -->
        <div class="d-flex flex-grow-1 overflow-hidden">

            <!-- SIDEBAR -->
            <aside class="bg-body-tertiary border-end p-3"
                   style="width: 280px; min-width: 240px;">

                <div class="list-group list-group-flush gap-2">

                    {% for spisok in movie_lists.results %}
                        <a class="list-group-item list-group-item-action bg-body-secondary border-1 rounded-2 fw-semibold text-body-secondary"
                           hx-post="{% url 'vault:list_get_movies' spisok.id %}"
                           hx-trigger="click"
                           hx-target="#main-content"
                           role="button"
                        >
                            {{ spisok.name }} <small><i class="bi bi-trash3-fill"></i></small>
                        </a>
                    {% endfor %}

                </div>
            </aside>


            <!-- CONTENT AREA -->
            <main class="flex-grow-1 p-3 overflow-auto" id="main-content">

                <!-- GRID WRAPPER -->
                <div class="d-grid gap-3"
                     style="grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));">

                    <!-- MOVIE CARD PLACEHOLDERS -->
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>
                    <div class="bg-secondary bg-opacity-10 rounded" style="height: 240px;"></div>


                </div>

            </main>

        </div>
    </div>

<style>
    #main-content {
        height: auto;
        overflow: visible;
    }
</style>


{% endblock %}