core/urls.py
from django.urls import path
from core import views
from core import auth
from django.contrib.auth.views import LoginView


app_name = "core"

urlpatterns = [
    path('preferences/', views.user_preferences_update, name='user_preferences'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth.user_logout, name="logout"),
    path('tst/', views.tst, name='tst'),
    path('register/', auth.register_user, name='register'),
    path('delete_account/', auth.delete_account, name='delete_account'),
]

movie_filter_pro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviefilter.urls')),
    path('', include('tmdb_adapter.urls')),
    path('', include('core.urls')),
    path('', include('vault.urls')),
    path('', include('plex.urls')),
    path('', include('tmdb.urls')),
    path('', include('kinorium.urls')),
    path('', include('web_logger.urls')),
    path('', include('kinozal_scan.urls')),
]


if settings.ENABLE_BROWSER_RELOAD:
    # django_browser_reload APP
    urlpatterns += path("__reload__/", include("django_browser_reload.urls")),
if settings.ENABLE_DEBUG_TOOLBAR:
    # add debug_toolbar APP
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
if settings.DEBUG:
    # add serve for Media during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # add serve for Static during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vault/urls.py
from django.urls import path
from . import views

app_name = 'vault'

urlpatterns = [
    # Главная страница и список фильмов
    path('', views.MovieListView.as_view(), name='movie_list'),
    path('movies/', views.MovieListView.as_view(), name='movie_list'),
    path('movies/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('genre/<slug:slug>/', views.MovieByGenreView.as_view(), name='movie_by_genre'),

    # Поиск
    path('search/', views.SearchView.as_view(), name='search'),

    # Персоны
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='person_detail'),

    # Пользовательские списки
    path('my-lists/', views.MyListsView.as_view(), name='my_lists'),
    path('list/<int:pk>/', views.ListDetailView.as_view(), name='list_detail'),
    path('list/create/', views.ListCreateView.as_view(), name='list_create'),
    path('list/<int:pk>/edit/', views.ListUpdateView.as_view(), name='list_edit'),
    path('list/<int:pk>/delete/', views.ListDeleteView.as_view(), name='list_delete'),

    # HTMX эндпоинты для быстрых действий
    path('htmx/toggle-status/', views.toggle_movie_status, name='htmx_toggle_status'),
    path('htmx/rate-movie/', views.rate_movie, name='htmx_rate_movie'),
    path('htmx/remove-rating/', views.remove_rating, name='htmx_remove_rating'),
    path('htmx/add-to-list/', views.add_to_list, name='htmx_add_to_list'),
    path('htmx/remove-from-list/', views.remove_from_list, name='htmx_remove_from_list'),
    path('htmx/toggle-list-privacy/', views.toggle_list_privacy, name='htmx_toggle_list_privacy'),

    # Отзывы
    path('movie/<slug:slug>/review/', views.CreateReviewView.as_view(), name='create_review'),
    path('htmx/like-review/<int:pk>/', views.like_review, name='htmx_like_review'),
]

vault/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, JsonResponse
from django.db.models import Q, Avg, Count
from django.contrib import messages
from django.core.paginator import Paginator

from .models import (
    Movie, Person, Genre, UserList, UserListMovie,
    Rating, Review, MoviePerson
)
from .services.movie_status_service import MovieStatusService


class MovieListView(ListView):
    """Список всех фильмов"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        queryset = Movie.objects.filter(status='released').prefetch_related('genres', 'countries')

        # Сортировка
        order = self.request.GET.get('order', '-year')
        queryset = queryset.order_by(order)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['selected_genre'] = None
        return context


class MovieByGenreView(ListView):
    """Фильмы по жанру"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        self.genre = get_object_or_404(Genre, slug=self.kwargs['slug'])
        queryset = Movie.objects.filter(
            genres=self.genre,
            status='released'
        ).prefetch_related('genres', 'countries')

        order = self.request.GET.get('order', '-year')
        queryset = queryset.order_by(order)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['selected_genre'] = self.genre
        return context


class MovieDetailView(DetailView):
    """Детальная страница фильма"""
    model = Movie
    template_name = 'vault/movie_detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie = self.object

        # Статус фильма у пользователя
        if self.request.user.is_authenticated:
            context['movie_status'] = MovieStatusService.get_movie_status(
                self.request.user, movie
            )
            context['user_rating'] = context['movie_status']['rating']
        else:
            context['movie_status'] = {
                'in_watched': False,
                'in_will_watch': False,
                'in_wont_watch': False,
                'in_favorites': False,
                'rating': None,
            }
            context['user_rating'] = None

        # Отзывы
        context['reviews'] = movie.reviews.select_related('user').prefetch_related('likes')[:5]

        return context


class SearchView(ListView):
    """Поиск фильмов"""
    model = Movie
    template_name = 'vault/movie_list.html'
    context_object_name = 'movies'
    paginate_by = 20

    def get_queryset(self):
        query = self.request.GET.get('q', '')

        if query:
            queryset = Movie.objects.filter(
                Q(title__icontains=query) |
                Q(original_title__icontains=query) |
                Q(description__icontains=query)
            ).prefetch_related('genres', 'countries')
        else:
            queryset = Movie.objects.none()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


class PersonDetailView(DetailView):
    """Страница персоны (актер, режиссер и т.д.)"""
    model = Person
    template_name = 'vault/person_detail.html'
    context_object_name = 'person'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        person = self.object

        # Все фильмы персоны
        all_movies = MoviePerson.objects.filter(
            person=person
        ).select_related('movie').order_by('-movie__year')

        context['all_movies'] = all_movies
        context['movies_count'] = all_movies.count()

        # По ролям
        context['actor_movies'] = all_movies.filter(role='actor')
        context['director_movies'] = all_movies.filter(role='director')
        context['producer_movies'] = all_movies.filter(role='producer')

        # Статистика
        context['roles_count'] = all_movies.values('role').distinct().count()

        # Годы карьеры
        years = all_movies.values_list('movie__year', flat=True)
        if years:
            context['career_years'] = max(years) - min(years)
        else:
            context['career_years'] = 0

        return context


class MyListsView(LoginRequiredMixin, ListView):
    """Все списки пользователя"""
    model = UserList
    template_name = 'vault/my_lists.html'
    context_object_name = 'user_lists'

    def get_queryset(self):
        return UserList.objects.filter(
            user=self.request.user
        ).prefetch_related('list_movies').order_by('order', '-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Разделяем системные и пользовательские списки
        all_lists = self.get_queryset()
        context['system_lists'] = all_lists.filter(is_system=True)
        context['custom_lists'] = all_lists.filter(is_system=False)

        return context


class ListDetailView(LoginRequiredMixin, DetailView):
    """Детальная страница списка"""
    model = UserList
    template_name = 'vault/list_detail.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        # Пользователь может видеть только свои списки (или публичные - добавить позже)
        return UserList.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_list = self.object

        # Фильмы из списка
        list_movies = UserListMovie.objects.filter(
            user_list=user_list
        ).select_related('movie').prefetch_related('movie__genres')

        # Сортировка
        order = self.request.GET.get('order', '-added_at')
        if order == '-added_at':
            list_movies = list_movies.order_by('-added_at')
        elif order == '-year':
            list_movies = list_movies.order_by('-movie__year')
        elif order == '-imdb_rating':
            list_movies = list_movies.order_by('-movie__imdb_rating')
        elif order == 'title':
            list_movies = list_movies.order_by('movie__title')

        context['list_movies'] = list_movies
        context['movies'] = Movie.objects.filter(
            id__in=list_movies.values_list('movie_id', flat=True)
        )

        # Статистика
        movies = context['movies']
        context['avg_duration'] = movies.aggregate(Avg('duration'))['duration__avg']
        context['avg_rating'] = movies.aggregate(Avg('imdb_rating'))['imdb_rating__avg']

        # Популярные жанры
        context['top_genres'] = Genre.objects.filter(
            movies__in=movies
        ).annotate(count=Count('movies')).order_by('-count')[:5]

        return context


class ListCreateView(LoginRequiredMixin, CreateView):
    """Создание нового списка"""
    model = UserList
    template_name = 'vault/list_create.html'
    fields = ['name', 'description', 'is_public']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.list_type = 'custom'
        form.instance.is_system = False
        messages.success(self.request, 'Список успешно создан!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:list_detail', kwargs={'pk': self.object.pk})


class ListUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование списка"""
    model = UserList
    template_name = 'vault/list_create.html'
    fields = ['name', 'description', 'is_public']

    def get_queryset(self):
        # Только свои списки и не системные
        return UserList.objects.filter(user=self.request.user, is_system=False)

    def form_valid(self, form):
        messages.success(self.request, 'Список успешно обновлен!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:list_detail', kwargs={'pk': self.object.pk})


class ListDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление списка"""
    model = UserList
    success_url = reverse_lazy('vault:my_lists')

    def get_queryset(self):
        # Только свои списки и не системные
        return UserList.objects.filter(user=self.request.user, is_system=False)

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Список успешно удален!')
        return super().delete(request, *args, **kwargs)


class CreateReviewView(LoginRequiredMixin, CreateView):
    """Создание отзыва"""
    model = Review
    fields = ['title', 'text', 'review_type']

    def form_valid(self, form):
        movie = get_object_or_404(Movie, slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        form.instance.movie = movie
        messages.success(self.request, 'Отзыв успешно опубликован!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('vault:movie_detail', kwargs={'slug': self.kwargs['slug']})


# ============== HTMX Views ==============

@login_required
def toggle_movie_status(request):
    """Переключить статус фильма (HTMX)"""
    if request.method == 'POST':
        movie_id = request.POST.get('movie_id')

vault/templates/vault/_header.html
{% load static %}

<div class="bg-light border-bottom mb-4">
    <div class="container">
        <div class="d-flex align-items-center py-3">
            <!-- Logo and Navigation -->
            <div class="me-auto d-flex align-items-center">
                <a href="{% url 'vault:movie_list' %}" class="text-decoration-none text-dark me-4">
                    <h4 class="mb-0">
                        <i class="bi bi-film"></i> Vault
                    </h4>
                </a>

                <nav class="nav">
                    <a class="nav-link {% if request.resolver_match.url_name == 'movie_list' %}active fw-bold{% endif %}"
                       href="{% url 'vault:movie_list' %}">
                        <i class="bi bi-collection-play"></i> Фильмы
                    </a>

                    {% if user.is_authenticated %}
                        <a class="nav-link {% if request.resolver_match.url_name == 'my_lists' or request.resolver_match.url_name == 'list_detail' %}active fw-bold{% endif %}"
                           href="{% url 'vault:my_lists' %}">
                            <i class="bi bi-list-ul"></i> Мои списки
                        </a>
                    {% endif %}
                </nav>
            </div>

            <!-- Search Form -->
            <form class="d-flex" method="get" action="{% url 'vault:search' %}">
                <input class="form-control form-control-sm me-2"
                       type="search"
                       name="q"
                       placeholder="Поиск фильмов..."
                       value="{{ request.GET.q }}"
                       style="width: 300px;">
                <button class="btn btn-primary btn-sm" type="submit">
                    <i class="bi bi-search"></i>
                </button>
            </form>
        </div>
    </div>
</div>

<style>
    .nav-link.active {
        color: #0d6efd !important;
    }
</style>

vault/templates/vault/list_create.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    {% include "vault/_header.html" %}

    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'vault:my_lists' %}">Мои списки</a></li>
                        <li class="breadcrumb-item active">Создать список</li>
                    </ol>
                </nav>

                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title mb-4">Создать новый список</h2>

                        <form method="post" action="{% url 'vault:list_create' %}">
                            {% csrf_token %}

                            <!-- Название -->
                            <div class="mb-3">
                                <label for="listName" class="form-label">Название списка <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="listName" name="name"
                                       placeholder="Например: Лучшие фильмы 2000-х" required>
                                <div class="form-text">Придумайте название, которое отражает тему вашего списка</div>
                            </div>

                            <!-- Описание -->
                            <div class="mb-3">
                                <label for="listDescription" class="form-label">Описание</label>
                                <textarea class="form-control" id="listDescription" name="description" rows="4"
                                          placeholder="Опишите, какие фильмы войдут в этот список..."></textarea>
                                <div class="form-text">Необязательное поле, но поможет другим понять суть списка</div>
                            </div>

                            <!-- Приватность -->
                            <div class="mb-4">
                                <label class="form-label">Видимость списка</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_public" id="publicList" value="true">
                                    <label class="form-check-label" for="publicList">
                                        <strong>Публичный</strong>
                                        <br>
                                        <small class="text-muted">Список будет виден всем пользователям</small>
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_public" id="privateList" value="false" checked>
                                    <label class="form-check-label" for="privateList">
                                        <strong>Приватный</strong>
                                        <br>
                                        <small class="text-muted">Список будет виден только вам</small>
                                    </label>
                                </div>
                            </div>

                            <!-- Кнопки -->
                            <div class="d-flex gap-2">
                                <button type="submit" class="btn btn-primary">
                                    <i class="bi bi-check-circle"></i> Создать список
                                </button>
                                <a href="{% url 'vault:my_lists' %}" class="btn btn-outline-secondary">
                                    Отмена
                                </a>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Подсказки -->
                <div class="mt-4">
                    <div class="card bg-light">
                        <div class="card-body">
                            <h5 class="card-title">
                                <i class="bi bi-lightbulb text-warning"></i> Советы по созданию списков
                            </h5>
                            <ul class="mb-0">
                                <li>Создавайте тематические списки: по жанрам, годам, режиссерам</li>
                                <li>Используйте описание для дополнительной информации</li>
                                <li>Публичные списки могут быть полезны другим пользователям</li>
                                <li>Вы всегда можете изменить название и описание позже</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

vault/templates/vault/movie_list.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    {% include "vault/_header.html" %}

    <div class="container mt-4">
        <!-- Заголовок и фильтры -->
        <div class="row mb-4">
            <div class="col-md-8">
                <h1 class="mb-3">Фильмы</h1>
            </div>
            <div class="col-md-4">
                <form method="get" action="{% url 'vault:search' %}" class="d-flex">
                    <input class="form-control me-2" type="search" name="q" placeholder="Поиск фильмов..." value="{{ request.GET.q }}">
                    <button class="btn btn-primary" type="submit">
                        <i class="bi bi-search"></i>
                    </button>
                </form>
            </div>
        </div>

        <!-- Фильтры по жанрам -->
        <div class="mb-4">
            <div class="btn-group flex-wrap" role="group">
                <a href="{% url 'vault:movie_list' %}" class="btn btn-sm {% if not selected_genre %}btn-primary{% else %}btn-outline-primary{% endif %}">
                    Все
                </a>
                {% for genre in genres %}
                    <a href="{% url 'vault:movie_by_genre' genre.slug %}"
                       class="btn btn-sm {% if selected_genre.id == genre.id %}btn-primary{% else %}btn-outline-primary{% endif %}">
                        {{ genre.name }}
                    </a>
                {% endfor %}
            </div>
        </div>

        <!-- Сортировка -->
        <div class="mb-3">
            <small class="text-muted me-3">Сортировка:</small>
            <a href="?order=-year" class="badge bg-secondary text-decoration-none me-2">По году ↓</a>
            <a href="?order=year" class="badge bg-secondary text-decoration-none me-2">По году ↑</a>
            <a href="?order=-imdb_rating" class="badge bg-secondary text-decoration-none me-2">По рейтингу ↓</a>
            <a href="?order=title" class="badge bg-secondary text-decoration-none">По названию</a>
        </div>

        <!-- Список фильмов -->
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-5 g-4">
            {% for movie in movies %}
                <div class="col">
                    <div class="card h-100 shadow-sm movie-card">
                        <a href="{% url 'vault:movie_detail' movie.slug %}" class="text-decoration-none">
                            {% if movie.poster %}
                                <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.title }}" style="height: 300px; object-fit: cover;">
                            {% else %}
                                <div class="card-img-top bg-secondary d-flex align-items-center justify-content-center" style="height: 300px;">
                                    <i class="bi bi-film" style="font-size: 3rem; color: #fff;"></i>
                                </div>
                            {% endif %}
                        </a>

                        <div class="card-body p-2">
                            <a href="{% url 'vault:movie_detail' movie.slug %}" class="text-decoration-none text-dark">
                                <h6 class="card-title mb-1" style="font-size: 0.9rem;">{{ movie.title }}</h6>
                            </a>
                            <p class="card-text mb-1">
                                <small class="text-muted">{{ movie.year }}</small>
                                {% if movie.imdb_rating %}
                                    <span class="badge bg-warning text-dark ms-1">★ {{ movie.imdb_rating }}</span>
                                {% endif %}
                            </p>
                            <p class="card-text mb-0">
                                <small class="text-muted">
                                    {% for genre in movie.genres.all|slice:":2" %}
                                        {{ genre.name }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </small>
                            </p>
                        </div>

                        <!-- Быстрые действия -->
                        {% if user.is_authenticated %}
                            <div class="card-footer bg-transparent border-0 p-2 pt-0">
                                <div class="btn-group btn-group-sm w-100" role="group">
                                    <button type="button" class="btn btn-outline-secondary" title="Буду смотреть">
                                        <i class="bi bi-bookmark"></i>
                                    </button>
                                    <button type="button" class="btn btn-outline-danger" title="Избранное">
                                        <i class="bi bi-heart"></i>
                                    </button>
                                    <button type="button" class="btn btn-outline-success" title="Просмотрено">
                                        <i class="bi bi-check-circle"></i>
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <div class="col-12">
                    <div class="alert alert-info">
                        Фильмы не найдены.
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Пагинация -->
        {% if movies.has_other_pages %}
            <nav aria-label="Навигация по страницам" class="mt-5">
                <ul class="pagination justify-content-center">
                    {% if movies.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">Первая</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ movies.previous_page_number }}">Предыдущая</a>
                        </li>
                    {% endif %}

                    {% for num in movies.paginator.page_range %}
                        {% if movies.number == num %}
                            <li class="page-item active">
                                <span class="page-link">{{ num }}</span>
                            </li>
                        {% elif num > movies.number|add:'-3' and num < movies.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if movies.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ movies.next_page_number }}">Следующая</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ movies.paginator.num_pages }}">Последняя</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>

    <style>
        .movie-card {
            transition: transform 0.2s;
        }
        .movie-card:hover {
            transform: translateY(-5px);
        }
    </style>
{% endblock %}