core/urls.py
from django.urls import path
from core import views
from core import auth
from django.contrib.auth.views import LoginView


app_name = "core"

urlpatterns = [
    path('preferences/', views.user_preferences_update, name='user_preferences'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth.user_logout, name="logout"),
    path('tst/', views.tst, name='tst'),
    path('register/', auth.register_user, name='register'),
    path('delete_account/', auth.delete_account, name='delete_account'),
]

kinorium/urls.py
from django.urls import path
from kinorium import views
from kinorium import htmx_views


app_name = "kinorium"

urlpatterns = [
    path('table/', views.table, name='table'),
]

htmx = [
    path('kinorium_table_data/', htmx_views.kinorium_table_data, name='table_data'),
    path('kinorium_search/<int:kinozal_id>', htmx_views.kinorium_search, name='search'),
]

urlpatterns += htmx

movie_filter_pro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moviefilter.urls')),
    path('', include('tmdb_adapter.urls')),
    path('', include('core.urls')),
    path('', include('vault.urls')),
    path('', include('plex.urls')),
    path('', include('tmdb.urls')),
    path('', include('kinorium.urls')),
    path('', include('web_logger.urls')),
    path('', include('kinozal_scan.urls')),
]


if settings.ENABLE_BROWSER_RELOAD:
    # django_browser_reload APP
    urlpatterns += path("__reload__/", include("django_browser_reload.urls")),
if settings.ENABLE_DEBUG_TOOLBAR:
    # add debug_toolbar APP
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
if settings.DEBUG:
    # add serve for Media during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # add serve for Static during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tmdb/urls.py
from django.urls import path
from tmdb import views

app_name = "tmdb"

urlpatterns = [
    path('tmdb/', views.tmdb_section, name='tmdb'),
    path('search_movies_dropdown/', views.search_movies_dropdown, name='search_movies_dropdown'),
    path('search_movies_fullpage/', views.search_movies_fullpage, name='search_movies_fullpage'),
    path('movie/<int:movie_id>/', views.movie, name='movie'),
    path('list_get_movies/<int:list_id>/', views.list_get_movies, name='list_get_movies'),

    path('list_create/<str:list_name>', views.list_create, name='list_create'),
    path('list_delete/<int:list_id>/', views.list_delete, name='list_delete'),
    path('list_rename/<int:list_id>/', views.list_rename, name='list_rename'),
]

tmdb_adapter/urls.py
from django.urls import path
from . import auth, views

app_name = 'tmdb-adapter'

urlpatterns = [

    # auth
    path("tmdb/auth/", auth.tmdb_auth, name="auth"),
    path("tmdb/auth/create_auth_link/", auth.tmdb_start, name="start"),
    path("tmdb/auth/approve_link/", auth.tmdb_approve, name="approve"),
    path("tmdb/auth/logout/", auth.tmdb_logout, name="logout"),

    # Страницы списков
    # path("tmdb/lists/", views.list_list, name="list_list"),
    # path("tmdb/lists/create/", views.list_create, name="list_create"),
    # path("tmdb/lists/<int:list_id>/", views.list_detail, name="list_detail"),
    #
    # # Операции со списками
    # path("tmdb/lists/<int:list_id>/rename/", views.list_rename, name="list_rename"),
    # path("tmdb/lists/<int:list_id>/delete/", views.list_delete, name="list_delete"),
    #
    # # Фильмы внутри списка (HTML фрагменты для HTMX)
    # path("tmdb/lists/<int:list_id>/items/", views.list_items_partial, name="list_items"),
    # path("tmdb/lists/<int:list_id>/items/add/", views.list_item_add, name="list_item_add"),
    # path(
    #     "tmdb/lists/<int:list_id>/items/<int:item_id>/delete/",
    #     views.list_item_delete,
    #     name="list_item_delete"
    # ),
]

core/models.py
from django.db import models


class Country(models.Model):
    """Модель стран производства"""
    name = models.CharField('Название', max_length=100, unique=True)
    code = models.CharField('Код', max_length=2, unique=True, blank=True)

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'
        ordering = ['name']

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from moviefilter.models import UserPreferences
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, HTML, Field


class PreferencesForm(forms.ModelForm):
    class Meta:
        model = UserPreferences
        fields = ['last_scan', 'scan_from_page', 'plex_address', 'plex_token', 'countries', 'genres', 'max_year',
                  'min_rating', 'kinozal_domain', 'low_countries', 'low_genres', 'low_max_year', 'low_min_rating',
                  'tmdb_api_key', 'tmdb_v4_read_access_token', 'tmdb_v4_authenticated_access_token',
                  'ignore_title', 'cookie_pass', 'cookie_uid',
                  'torrents_hotfolder']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-md-9'
        # self.helper.add_input(Submit('submit', 'Save11'))

        self.fields["tmdb_v4_authenticated_access_token"].disabled = True
        self.fields["tmdb_v4_authenticated_access_token"].label = "Authenticated Write Access Token"

        self.helper.layout = Layout(
            HTML("""<h3>Last scan</h3><hr>"""),
            Field("last_scan"),
            Field("scan_from_page"),
            HTML("""<h3>Torrent</h3><hr>"""),
            Field("cookie_pass"),
            Field("cookie_uid"),
            Field("kinozal_domain"),
            Field("torrents_hotfolder"),
            HTML("""<h3>Plex</h3><hr>"""),
            Field("plex_address"),
            Field("plex_token"),
            HTML("""
                <h3>TMDB</h3>
                <i>v4_read_access_token берется с сайт, v4_authenticated_access_token клиет получает после аутентификации</i>
                <hr>
            """),
            Field("tmdb_api_key"),
            Field("tmdb_v4_read_access_token"),
            Field("tmdb_v4_authenticated_access_token"),
            HTML("""<h3>Strict rules</h3>
                <i>Сначала из всего списка удаляеся все, что содержит эти страны/жанры или менее года/рейтинга</i>
                <hr>
                """),
            Field("countries"),
            Field("genres"),
            Field("max_year"),
            Field("min_rating"),
            HTML("""
                <h3>Low priority</h3>
                <i>Оставшиеся фильмы помечаются как "Low priority", если они содержат указанные страны/жанры, или менее года/рейтинга</i>
                <hr>
            """),
            Field("low_countries"),
            Field("low_genres"),
            Field("low_max_year"),
            Field("low_min_rating"),
            HTML("""
                <h3>Ignore words from titles</h3>
                <i>Separete by comma</i>
                <hr>
            """),
            Field("ignore_title"),
            Submit("submit", "Save", css_class=""),
        )

    # def clean_zoom(self):
    #     zoom = int(self.cleaned_data["zoom"])
    #     if zoom < 70 or zoom > 130:
    #         raise ValidationError("Zoom not in range [70-130]!")
    #
    #     # Always return a value to use as the new cleaned data, even if
    #     # this method didn't change it.
    #     return zoom

core/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import PreferencesForm
from moviefilter.models import UserPreferences


@login_required()
def user_preferences_update(request):
    # deprecated  user = User.objects.get(pk=request.user.pk)
    pref = UserPreferences.get()
    form = PreferencesForm(request.POST or None, instance=pref)

    if request.method == 'POST':
        if form.is_valid():
            # pref = UserPreferences.objects.get_or_create(user=request.user)
            pref.last_scan = form.cleaned_data['last_scan']
            pref.scan_from_page = form.cleaned_data['scan_from_page']
            pref.countries = form.cleaned_data['countries']
            pref.genres = form.cleaned_data['genres']
            pref.max_year = int(form.cleaned_data['max_year'])
            pref.min_rating = float(form.cleaned_data['min_rating'])

            pref.low_countries = form.cleaned_data['low_countries']
            pref.low_genres = form.cleaned_data['low_genres']
            pref.low_max_year = int(form.cleaned_data['low_max_year'])
            pref.low_min_rating = float(form.cleaned_data['low_min_rating'])

            pref.kinozal_domain = form.cleaned_data['kinozal_domain']

            pref.plex_address = form.cleaned_data['plex_address']
            pref.plex_token = form.cleaned_data['plex_token']

            pref.save()
            return redirect(reverse('core:user_preferences'))
    return render(request, 'preferences_update_form.html', {'form': form})


def tst(request):
    if request.method == 'POST':
        print(request.POST)
    if request.method == 'GET':
        print(request.GET)

    if request.htmx:
        return HttpResponse('SOME HTMX DATA')
    else:
        return render(request, 'testing.html')

core/templates/base.html
{# Bootstrap CSS template#}

{% load i18n %}
{% load static %}
{#{% load admin_urls %}#}
{% load compress %}


<!DOCTYPE html >
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Popper [before bootstrap]-->
    <script src="https://unpkg.com/@popperjs/core@2"></script>

    <!-- BOOTSTRAP -->
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %} ">
    <script defer src="{% static 'bootstrap/bootstrap-theme-toggler.js' %}"></script>

    {% comment %}    <!-- ALPINE JS -->
    <script defer src="{% static 'alpine/alpine.min.js' %}"></script>{% endcomment %}

    <!-- HTMX -->
    <script src="{% static 'htmx/htmx.min.js' %}"></script>

    <!-- Hyperscript -->
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="{% static 'bootstrap-icons/bootstrap-icons.min.css' %} ">

    <!-- Sweet alert 2 -->
    <link rel="stylesheet" href="{% static 'sweetalert2/bootstrap-4.min.css' %}">
    <script src="{% static 'sweetalert2/sweetalert2.js' %}"></script>

    <!-- hint.ccs (tooltips) -->
    <link href="{% static 'hint.css-2.7.0/hint.base.min.css' %}" rel="stylesheet">

    {% comment %}    {% compress css %}
        <link type="text/x-scss" href="{% static 'style.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}{% endcomment %}

    <script src="{% static 'toasts.js' %}"></script>

    {% comment %}    <!-- jQuery, for depends: Select2 -->
    <script src="{% static 'jslib/jquery-3.7.1.js' %}"></script>{% endcomment %}

    {% comment %}    <!-- Select2 -->
    <link href="{% static 'select2/select2.min.css' %}" rel="stylesheet" />
    <script src="{% static 'select2/select2.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'select2/select2-bootstrap-5-theme.min.css' %}" />{% endcomment %}

    <title>{% block title %}KinoRSS{% endblock %}</title>
    {% block css %}{% endblock %}




</head>

{% comment %}
    DEPRECATED - Заменено на js скрипт, потому что этот старый метод не пригоден для ОБНОВЛЯЮЩИХСЯ частей страницы,
    в них нужно динамически обновлять токен. Например, в подгружающихся частях основного списка фильмов.
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

{% endcomment %}

<body>

<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

{% if is_dev %}
{#<div class="alert center-aligned alert-success" role="alert">#}
<div class="alert center-aligned alert-success sticky-top py-2 " style="z-index: 1050;" role="alert">
    <strong>DEVELOPER ENVIRONMENT</strong>
</div>
{% endif %}

{% include "header.html" %}
{% block body %}  {% endblock %}


{% block scripts %}
    {% comment %}   <!-- My toast injecting -->
    <script src="{% static 'js/toasts.js' %}" defer></script>{% endcomment %}



{#отказался от bootstrap tooltips#}
{% comment %}    <script>
        // Initialize bootstrap tooltips (need load popper.js)
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>{% endcomment %}
{% endblock %}


{% comment %}
<div x-data="{ open: false }">
    <button class="btn btn-success" type="button" @click="open = ! open">Alpine JS Demo -> Expand</button>

    <div x-show="open">
        Content...
    </div>
</div>{% endcomment %}

{% block js %}{% endblock %}

<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
       // Пытаемся получить CSRF токен либо из скрытого поля формы, либо из cookie
       const token = document.querySelector('[name=csrfmiddlewaretoken]')?.value ||
                     (document.cookie.match(/csrftoken=([^;]+)/) || [])[1];

       if (token) {
           event.detail.headers['X-CSRFToken'] = token;
       }
   });
</script>

</body>

</html>

core/templates/header.html
{# Bootstrap CSS template#}
{% load i18n %}
{% load static %}
{% load active %}
{% load admin_urls %}

{% block navbar %}

    <nav class="navbar navbar-expand ">
        <div class="container-fluid m-2 p-2 border border-1 rounded">

            <a class="navbar-brand" href="/">
                <img src="{% static 'ico/icons8-movie-64.png' %}" alt="Logo" width="30" height="24"
                     class="d-inline-block align-text-top">
                KinoRSS
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link {% active 'rss' %}"
                           href="{% url 'rss' %}"><i class="bi-database me-1"></i>Kinozal</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% active 'vault:movie_list' %}"
                           href="{% url 'vault:movie_list' %}"><i class="bi-database me-1"></i>Vault</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% active 'table' %}"
                           href="{% url 'kinorium:table' %}"><i class="bi-database me-1"></i>Kinorium</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% active 'tmdb' %}"
                           href="{% url 'tmdb:tmdb' %}"><i class="bi-database me-1"></i>TMDB</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% active 'plex_section' %}"
                           href="{% url 'plex_section' %}"><i class="bi-database me-1"></i>Plex</a>
                    </li>

                    <li class="nav-item">
                       <a class="nav-link {% active 'scan_page' %}"
                           href="{% url 'scan_page' %}"><i class="bi-database me-1"></i>Scan</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link {% active 'tst' %}"
                           href="{% url 'core:tst' %}"><i class="bi-database me-1"></i>Tst area</a>
                    </li>

                </ul>

                <div class="Header-item px-2">
                    <small class="text-muted">v. {{ VERSION }}</small>
                </div>

                {% if user.is_authenticated %}
                    <div class="Header-item m-lg-1">
                        <span class="badge text-bg-success"><i class="bi-person-check-fill"></i> {{ user.username }}</span>
                    </div>

                    <div class="Header-item">
                        <a href="{% url 'tmdb-adapter:auth' %}" class="btn btn-sm btn-outline-secondary mx-1 {% active 'tmdb_auth' %}" type="button" >
                            TMDB</a>
                    </div>

                    <div class="Header-item">
                        <a href="{% url 'core:user_preferences' %}" class="btn btn-sm btn-outline-secondary mx-1 {% active 'preferences' %}" type="button" >
                            {% comment %}<i class="bi-person-check-fill" style="color: #66f566;"></i>{% endcomment %}
                            Preferences</a>
                    </div>

                    <div class="Header-item">
                        <a href="{% url 'core:logout' %}?next={% url 'core:login' %}" class="btn btn-sm btn-outline-secondary mx-1" type="button">
                        {% comment %}<a href="{% url 'core:logout' %}" class="btn btn-sm btn-outline-secondary mx-1" type="button">{% endcomment %}
                            <i class="bi bi-box-arrow-left"></i>
                            Logout</a>
                    </div>

                {% else %}

                    <form class="d-flex mx-2" name='AuthenticationForm' method="post" action="{% url 'core:login' %}">
                        {% csrf_token %}
                        <input type="text" class="form-control form-control-sm me-2" id="input1" placeholder="Username"
                               name="username">
                        <input type="password" class="form-control form-control-sm me-2" id="input2"
                               placeholder="Password" name="password">
                        <button type="submit" class="btn btn-outline-secondary btn-sm">Login</button>
                    </form>

                {% endif %}

                <button class="btn btn-outline" data-bs-theme-value="" id="theme-toggler">
                    <i class="bi bi-lightbulb"></i>
                </button>

            </div>
        </div>
    </nav>

    <style>
        .active {
            background: #97c2c2;
            border-radius: 5px;
        }
    </style>

{% endblock %}

core/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body %}
    <div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
        <div class="text-center shadow-lg p-5 rounded-4 border bg-light" style="max-width: 500px;">

            <div class="mb-4">
                <i class="bi bi-person-circle" style="font-size: 4rem; color: #6c757d;"></i>
                <h1 class="fw-bold display-6 mt-2">Добро пожаловать</h1>
            </div>

            <div class="d-grid gap-3">
                <a href="{% url 'core:login' %}" class="btn btn-outline-dark btn-lg py-3 fw-semibold">
                    Войти в аккаунт
                </a>

                <div class="d-flex align-items-center my-2">
                    <hr class="flex-grow-1">
                    <span class="mx-3 text-muted">или</span>
                    <hr class="flex-grow-1">
                </div>

                <a href="{% url 'core:register' %}" class="btn btn-primary btn-lg py-3 fw-semibold shadow-sm">
                    Зарегистрироваться
                </a>
            </div>

            <p class="mt-4 text-muted small">
                Выберите действие, чтобы продолжить работу с сервисом
            </p>
        </div>
    </div>
{% endblock %}

{% comment %}
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body %}
<div class="container d-flex  d-flex justify-content-center" style="min-height: 80vh;">

    <div class="d-flex align-items-center" style="font-size: 3em; color: #5c636a">
        <div style="border: solid red; padding: 10px; border-radius: 10px;">
            Please login
        </div>
        or register
        <a class="btn btn-primary btn-sm" href="{% url 'core:register' %}" role="button">Register</a>
    </div>

</div>
{% endblock %}
{% endcomment %}

core/templates/preferences_update_form.html
{% extends 'base.html' %}
{% block title %}Edit Preferensies{% endblock %}
{% load crispy_forms_tags %}


{% block body %}
    <div class="container">

        <div class="col-6 offset-3">

            <div class="row p-0">
                <form method="post">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>


            <div class="row mt-4">
                <h3>Clear RSS database</h3>
                <hr>
                <div>
                    <button type="submit" class="disabled btn btn-danger btn-lg" name="reset"
                            hx-delete="{% url 'reset_rss' %}"
                            hx-swap=none
                            hx-confirm="This destroy all scanned movies!"
                    ><i class="bi bi-trash3-fill"></i> RESET
                    </button>
                </div>
            </div>

            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger mt-5" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">
                DELETE ACCOUNT
            </button>

        </div>
    </div>


    <!-- Toast template -->
    <div data-toast-container class="toast-container position-fixed top-0 end-0 p-3">
        <div data-toast-template class="toast align-items-center border-0" role="alert" aria-live="assertive"
             aria-atomic="true">
            <div class="d-flex">
                <div data-toast-body class="toast-body"></div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                        aria-label="Close"></button>
            </div>
        </div>
    </div>
    <!-- end Toast template -->

    <!-- Delete Account Modal -->
    <div class="modal fade" id="deleteAccountModal" tabindex="-1" aria-labelledby="deleteAccountModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteAccountModalLabel">Удаление аккаунта</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form method="post" action="{% url 'core:delete_account' %}">
              {% csrf_token %}
              <div class="modal-body">
                <p class="text-danger fw-bold">Это действие необратимо! Все ваши данные будут удалены.</p>
                <div class="mb-3">
                    <label for="confirmUsername" class="form-label">Введите ваше имя пользователя (<b>{{ request.user.username }}</b>) для подтверждения:</label>
                    <input type="text" class="form-control" id="confirmUsername" name="username" required autocomplete="off">
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <button type="submit" class="btn btn-danger">Удалить навсегда</button>
              </div>
          </form>
        </div>
      </div>
    </div>

    <script>
        document.addEventListener("htmx:confirm", function (e) {
            e.preventDefault()
            Swal.fire({
                title: "Proceed?",
                text: `${e.detail.question}`,
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) e.detail.issueRequest(true) // use true to skip window.confirm
            })
        })
    </script>

{% endblock %}

core/templates/register.html
{% extends "base.html" %}
{% load static %}

{% block body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <div class="card shadow-sm">
                    <div class="card-body p-4">
                        <h2 class="card-title text-center mb-4">Регистрация</h2>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                    {{ message }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form method="post" class="needs-validation">
                            {% csrf_token %}

                            <div class="mb-3">
                                <label for="username" class="form-label">Имя пользователя</label>
                                <input type="text" name="username" class="form-control" id="username" placeholder="ivan_ivanov" required>
                            </div>

                            <div class="mb-3">
                                <label for="email" class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com" required>
                            </div>

                            <div class="mb-3">
                                <label for="password1" class="form-label">Пароль</label>
                                <input type="password" name="password1" class="form-control" id="password1" required>
                            </div>

                            <div class="mb-4">
                                <label for="password2" class="form-label">Подтвердите пароль</label>
                                <input type="password" name="password2" class="form-control" id="password2" required>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary btn-lg">Зарегистрироваться</button>
                            </div>
                        </form>

                        <hr class="my-4">

                        <p class="text-center mb-0">
                            Уже есть аккаунт? <a href="{% url 'core:login' %}" class="text-decoration-none">Войти</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/testing.html
{% extends "base.html" %}
{% load static %}

{% block body %}


    <div class="result"></div>

{% endblock %}